// Auto-generated by: npm run sanity:types
// Run after schema changes: sanity typegen generate

export interface SanityDocument {
  _id: string
  _type: string
  _createdAt: string
  _updatedAt: string
  _rev: string
}

export interface Slug {
  current: string
  _type: 'slug'
}

export interface SanityImageAsset {
  url: string
  _type: 'reference'
  _ref: string
}

export interface Tag extends SanityDocument {
  _type: 'tag'
  title?: string
  slug?: Slug
}

export interface Author extends SanityDocument {
  _type: 'author'
  name?: string
  bio?: string
  image?: { asset: SanityImageAsset }
}

export interface Project extends SanityDocument {
  _type: 'project'
  title?: string
  slug?: Slug
  description?: string
  content?: unknown[]
  featuredImage?: { asset: SanityImageAsset }
  tags?: Tag[]
  liveUrl?: string
  repoUrl?: string
  publishedAt?: string
}

export interface Post extends SanityDocument {
  _type: 'post'
  title?: string
  slug?: Slug
  excerpt?: string
  content?: unknown[]
  author?: Author
  tags?: Tag[]
  publishedAt?: string
}

export interface SiteSettings extends SanityDocument {
  _type: 'siteSettings'
  siteName?: string
  description?: string
  logo?: { asset: SanityImageAsset }
  socialLinks?: Array<{ platform: string; url: string }>
}
