export const tokens = {
  colors: {
    brand: {
      accent: '#e34d2a',
      accentSoft: '#e34d2a1a',
      accentLine: '#e34d2a33',
      statusOk: '#22c55e',
      spotify: '#1ed760',
    },
    dark: {
      canvas: '#0f0f10',
      surface1: 'rgba(255,255,255,0.04)',
      surface2: 'rgba(255,255,255,0.06)',
      surfaceInput: 'rgba(255,255,255,0.03)',
      hairline: 'rgba(255,255,255,0.08)',
      hairlineMid: 'rgba(255,255,255,0.10)',
      dockBg: 'rgba(20,20,22,0.70)',
      fg1: '#ffffff',
      fg2: 'rgba(255,255,255,0.75)',
      fg3: 'rgba(255,255,255,0.55)',
      fg4: 'rgba(255,255,255,0.40)',
      hero: '#e34d2a',
    },
    light: {
      canvas: '#ffffff',
      surface1: 'rgba(0,0,0,0.025)',
      surface2: 'rgba(0,0,0,0.05)',
      surfaceInput: 'rgba(0,0,0,0.02)',
      hairline: 'rgba(0,0,0,0.08)',
      hairlineMid: 'rgba(0,0,0,0.10)',
      dockBg: 'rgba(240,238,233,0.80)',
      fg1: '#111111',
      fg2: 'rgba(0,0,0,0.70)',
      fg3: 'rgba(0,0,0,0.55)',
      fg4: 'rgba(0,0,0,0.40)',
      hero: '#e34d2a1a',
    },
    compat: {
      background: 'var(--canvas)',
      foreground: 'var(--fg-1)',
      card: 'var(--surface-1)',
      cardForeground: 'var(--fg-1)',
      popover: 'var(--surface-1)',
      popoverForeground: 'var(--fg-1)',
      primary: 'var(--fg-1)',
      primaryForeground: 'var(--canvas)',
      secondary: 'var(--surface-2)',
      secondaryForeground: 'var(--fg-2)',
      muted: 'var(--surface-2)',
      mutedForeground: 'var(--fg-3)',
      border: 'var(--hairline)',
      input: 'var(--surface-input)',
      ring: 'var(--accent)',
      magicCardBg: {
        dark: 'rgba(255,255,255,0.05)',
        light: 'rgba(0,0,0,0.03)',
      },
    },
    magicCard: {
      gradient: 'rgba(227,77,42,0.08)',
    },
    borderBeam: {
      from: '#e34d2a',
      to: '#e34d2a33',
    },
    shimmer: '#e34d2a',
    contributions: [
      'rgba(255,255,255,0.05)',
      'rgba(227,77,42,0.20)',
      'rgba(227,77,42,0.40)',
      'rgba(227,77,42,0.70)',
      '#e34d2a',
    ] as readonly string[],
  },
  spacing: {
    1: '4px',
    2: '8px',
    3: '12px',
    4: '14px',
    5: '16px',
    6: '20px',
    7: '24px',
    8: '32px',
    9: '40px',
    10: '56px',
  },
  radii: {
    input: '8px',
    btn: '10px',
    image: '12px',
    card: '14px',
    dock: '18px',
    pill: '99px',
    base: '0.875rem',
  },
  typography: {
    size: {
      display: '56px',
      h1: '40px',
      h2: '28px',
      h3: '20px',
      body: '16px',
      bodySm: '14px',
      meta: '13.5px',
      label: '12px',
      micro: '11px',
    },
    lineHeight: {
      display: 1.05,
      heading: 1.15,
      body: 1.5,
    },
    family: {
      sans: "'Inter', system-ui, -apple-system, sans-serif",
      mono: "'JetBrains Mono', ui-monospace, SFMono-Regular, monospace",
    },
  },
  shadow: {
    dock: '0 12px 40px rgba(0,0,0,0.5)',
    dockLight: '0 12px 40px rgba(0,0,0,0.12)',
    glowOk: '0 0 8px rgba(34,197,94,0.6)',
  },
  overlay: {
    dark: 'rgba(0,0,0,0.65)',
    light: 'rgba(0,0,0,0.45)',
  },
  motion: {
    ease: 'cubic-bezier(0.4, 0, 0.2, 1)',
    fast: '0.15s',
    normal: '0.2s',
  },
} as const

export const cssVars = {
  root: {
    '--accent': tokens.colors.brand.accent,
    '--accent-soft': tokens.colors.brand.accentSoft,
    '--accent-line': tokens.colors.brand.accentLine,
    '--status-ok': tokens.colors.brand.statusOk,
    '--spotify': tokens.colors.brand.spotify,
    '--canvas': tokens.colors.dark.canvas,
    '--surface-1': tokens.colors.dark.surface1,
    '--surface-2': tokens.colors.dark.surface2,
    '--surface-input': tokens.colors.dark.surfaceInput,
    '--hairline': tokens.colors.dark.hairline,
    '--hairline-mid': tokens.colors.dark.hairlineMid,
    '--dock-bg': tokens.colors.dark.dockBg,
    '--fg-1': tokens.colors.dark.fg1,
    '--fg-2': tokens.colors.dark.fg2,
    '--fg-3': tokens.colors.dark.fg3,
    '--fg-4': tokens.colors.dark.fg4,
    '--t-display': tokens.typography.size.display,
    '--t-h1': tokens.typography.size.h1,
    '--t-h2': tokens.typography.size.h2,
    '--t-h3': tokens.typography.size.h3,
    '--t-body': tokens.typography.size.body,
    '--t-body-sm': tokens.typography.size.bodySm,
    '--t-meta': tokens.typography.size.meta,
    '--t-label': tokens.typography.size.label,
    '--t-micro': tokens.typography.size.micro,
    '--lh-display': String(tokens.typography.lineHeight.display),
    '--lh-heading': String(tokens.typography.lineHeight.heading),
    '--lh-body': String(tokens.typography.lineHeight.body),
    '--s-1': tokens.spacing[1],
    '--s-2': tokens.spacing[2],
    '--s-3': tokens.spacing[3],
    '--s-4': tokens.spacing[4],
    '--s-5': tokens.spacing[5],
    '--s-6': tokens.spacing[6],
    '--s-7': tokens.spacing[7],
    '--s-8': tokens.spacing[8],
    '--s-9': tokens.spacing[9],
    '--s-10': tokens.spacing[10],
    '--r-input': tokens.radii.input,
    '--r-btn': tokens.radii.btn,
    '--r-image': tokens.radii.image,
    '--r-card': tokens.radii.card,
    '--r-dock': tokens.radii.dock,
    '--r-pill': tokens.radii.pill,
    '--shadow-dock': tokens.shadow.dock,
    '--shadow-glow-ok': tokens.shadow.glowOk,
    '--ease': tokens.motion.ease,
    '--dur-fast': tokens.motion.fast,
    '--dur': tokens.motion.normal,
    '--hero': tokens.colors.dark.hero,
    '--overlay': tokens.overlay.dark,
  },
  light: {
    '--canvas': tokens.colors.light.canvas,
    '--surface-1': tokens.colors.light.surface1,
    '--surface-2': tokens.colors.light.surface2,
    '--surface-input': tokens.colors.light.surfaceInput,
    '--hairline': tokens.colors.light.hairline,
    '--hairline-mid': tokens.colors.light.hairlineMid,
    '--dock-bg': tokens.colors.light.dockBg,
    '--fg-1': tokens.colors.light.fg1,
    '--fg-2': tokens.colors.light.fg2,
    '--fg-3': tokens.colors.light.fg3,
    '--fg-4': tokens.colors.light.fg4,
    '--shadow-dock': tokens.shadow.dockLight,
    '--hero': tokens.colors.light.hero,
    '--overlay': tokens.overlay.light,
  },
} satisfies Record<string, Record<string, string>>
