import type { SocialItem } from '@/components/ui/social-feed-grid'

export const SOCIAL_DUMMY_ITEMS: SocialItem[] = [
  {
    id: 'yt-1',
    platform: 'youtube',
    url: '#',
    postedAt: '3 days ago',
    videoTitle: 'Building a production-ready AI agent from scratch with LangGraph',
    channelName: '@emudev',
    thumbnailHue: 0,
    duration: '12:34',
    views: 45200,
    likes: 2300,
    comments: 187,
  },
  {
    id: 'yt-2',
    platform: 'youtube',
    url: '#',
    postedAt: '2 weeks ago',
    videoTitle: 'Next.js 15 App Router: patterns I use in every production project',
    channelName: '@emudev',
    thumbnailHue: 220,
    duration: '18:45',
    views: 28800,
    likes: 1140,
    comments: 93,
  },
  {
    id: 'x-1',
    platform: 'x',
    url: '#',
    postedAt: '1 day ago',
    text: 'Just replaced 400 lines of custom validation with a single Zod schema wired through tRPC. Full type safety from DB → API → client. This is the way.',
    displayName: 'Esteban Montero',
    handle: '@emudevcc',
    likes: 312,
    comments: 28,
    shares: 67,
  },
  {
    id: 'x-2',
    platform: 'x',
    url: '#',
    postedAt: '5 days ago',
    text: 'Hot take: the best architectural decision you can make in 2025 is to NOT use microservices until you genuinely need them. A well-structured monolith ships 10x faster.',
    displayName: 'Esteban Montero',
    handle: '@emudevcc',
    likes: 891,
    comments: 104,
    shares: 213,
  },
  {
    id: 'rd-1',
    platform: 'reddit',
    url: '#',
    postedAt: '1 week ago',
    postTitle:
      "I built my portfolio with Next.js 15 + Sanity CMS + Tailwind v4 — here's what I learned about the new App Router",
    subreddit: 'nextjs',
    upvotes: 1547,
    comments: 89,
  },
  {
    id: 'rd-2',
    platform: 'reddit',
    url: '#',
    postedAt: '3 weeks ago',
    postTitle: 'The hidden performance wins from React Server Components that nobody talks about',
    subreddit: 'reactjs',
    upvotes: 2341,
    comments: 156,
  },
  {
    id: 'ig-1',
    platform: 'instagram',
    url: '#',
    postedAt: '4 days ago',
    text: 'Late night coding session. Working on a Three.js particle system for my portfolio — sometimes the best features happen after midnight.',
    handle: '@emudevcc',
    thumbnailHue: 280,
    likes: 447,
    comments: 23,
  },
  {
    id: 'tk-1',
    platform: 'tiktok',
    url: '#',
    postedAt: '6 days ago',
    videoTitle: 'How I structure my Next.js projects in 2025 #webdev #nextjs',
    handle: '@emudev',
    thumbnailHue: 175,
    duration: '0:58',
    views: 156000,
    likes: 8200,
    comments: 341,
  },
  {
    id: 'th-1',
    platform: 'threads',
    url: '#',
    postedAt: '2 days ago',
    text: 'What I wish I knew before shipping my first production app:\n\n1/ Boring technology > cutting-edge\n2/ Observability is not optional\n3/ Your README is your first onboarding doc\n4/ Write the migration story before the code',
    displayName: 'Esteban Montero',
    handle: '@emudevcc',
    likes: 203,
    comments: 41,
    shares: 88,
  },
]
